# lab store
model_reasoning_effort = "low"
check_for_update_on_startup = false

[projects."/private/var/folders/6f/1jf88sjj1yb6bwg4qkrtlxd00000gn/T/fm-lab-mate.WFxYuY"]
trust_level = "trusted"

[projects."/private/var/folders/6f/1jf88sjj1yb6bwg4qkrtlxd00000gn/T/fm-lab.xTBUN3/treehouse/.treehouse/alpha-b18597/1/alpha"]
trust_level = "trusted"

[tui]
screen_reader_detection_done = true

[tui.model_availability_nux]
"gpt-6.1-sol" = 1
